### PR TITLE
Add: support splitting long txt records over multiple values

### PR DESCRIPTION
**Pull request by lammas**

### CODE REVIEW

**Comment by reinefjord** [comment]
I'm amazed that someone on the internet found this so quickly and made a PR, thank you!

However, after some digging it seems like the correct way, or at least the most accepted method, to handle long dkim records is to split a single TXT record into multiple strings. I've pushed 7f9f51970addb2c2436bbb9363b8f0351a308001 which unfortunately obsoletes this PR, but I'm grateful that you brought this to my attention :)

**Comment by lammas** [comment]
This PR does indeed split it into multiple TXT records but the referenced commit seems to output just one TXT record even if the data is longer than 255. Am I missing something?

**Comment by reinefjord** [comment]
This was new to me, but a TXT record [can have one or more `<character-string>`s](https://www.rfc-editor.org/rfc/rfc1035#section-3.3.14) as data. [These character strings](https://www.rfc-editor.org/rfc/rfc1035#section-3.3) are what have a limit of 255 octets (plus a length octet each). The commit chunks the data into multiple length octets and character strings. The DNS record then looks like this:
```
_domainkey.example.org.	300	IN	TXT	"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6HjqwI0z30xieoBSm8ziawMRwqxtwhM1srL/DlOypea7nAqfYCrmb6kaRn24AGu1EQRfGZFDhNvLBuOQjajE7aoKeo/aYCd9C7YtbdG/XzUiudCIFhwMErOzKiXhgsaMK54wMXj+/7ya5RLK9zkI9UdHinn2RVWXguYn44hgEENNaX3qeWZ9lvIFAhWq48zhk" "c7doOuC0YGaOtAKTD/Mf61H5gaZygpDPlmyk98c47mzuPoM7EkELXc5ZJ9zvEeR6fmM4/yOrzSa37ybDbbLoXWg2pFP+aHI5bztUdPxhKINA08cQsS1xgrYWVP3kPhCYNuO547626QXgUJ4ed4pPQIDAQAB"
```
Note the cut in the middle of the data, separating the two strings. [DKIM then specifies](https://www.rfc-editor.org/rfc/rfc4871#section-3.6.2.2) that multiple strings are concatenated together.

**Comment by lammas** [comment]
Ah, thanks for pointing this out. I had no idea tinydns would start a second TXT value if it encountered another length marker. I figured it would have to be another TXT line in the data. :)

**Comment by reinefjord** [comment]
Yeah, had to read some RFCs and inspect DNS packets in Wireshark to figure out what to do and how, but it was an interesting journey :D

**Pull request closed without merging**
